### ISSUE TITLE
Do these hooks really need pkbuild-introspection-git?

### ISSUE THREAD

**Issue by marcelkorpel** [eli-schwartz/pkgbuilds#1]
In README.md you link to [pkgbuild-introspection-git](https://aur.archlinux.org/packages/pkgbuild-introspection-git) for creation of .SRCINFO files. However, as of version 7, `mksrcinfo` is provided by [pkgbuild-introspection](https://www.archlinux.org/packages/community/any/pkgbuild-introspection/) in \[community\] (though the description is misleading).

Do you really need pkgbuild-introspection-git?

**Comment by eli-schwartz** [comment]
Ah, thanks for reminding me. I set this up originally back before v7 was released, but neglected to update the readme. Fixed now.

**Comment by eli-schwartz** [comment]
Hah, sorry for the noise. I'm not used to GitHub listing every commit I rebased, just because I referenced the issue.

(usage typos...)
