### ISSUE TITLE
Checking out glibc-git's git source just hangs.

### ISSUE THREAD

**Issue by goddessfreya** [eli-schwartz/pkgbuilds#13]
Idk why, but it does. Changing the source's URL fixed it for me:

```
diff --git a/PKGBUILD b/PKGBUILD
index bc71d81..d67d8a9 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -20,7 +20,7 @@ conflicts=('glibc')
 backup=('etc/gai.conf' 'etc/nscd.conf')
 options=('staticlibs')
 install='glibc-git.install'
-source=('git+https://sourceware.org/git/glibc.git'
+source=('git+git://sourceware.org/git/glibc.git'
         'locale-gen'
         '0001-Revert-elf-Correct-absolute-SHN_ABS-symbol-run-time-.patch'
         'bz20338.patch')
```

**Comment by eli-schwartz** [comment]
It does clone for me, it's just... slow:

```
$ time git clone https://sourceware.org/git/glibc.git glibc-over-https
Cloning into 'glibc-over-https'...
Checking connectivity: 580355, done.
Updating files: 100% (17329/17329), done.

real	2m20.269s
user	3m54.191s
sys	0m4.952s
```

```
$ time git clone git://sourceware.org/git/glibc.git glibc-over-git
Cloning into 'glibc-over-git'...
remote: Enumerating objects: 580355, done.
remote: Counting objects: 100% (580355/580355), done.
remote: Compressing objects: 100% (76754/76754), done.
remote: Total 580355 (delta 492368), reused 580150 (delta 492204)
Receiving objects: 100% (580355/580355), 175.01 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (492368/492368), done.
Updating files: 100% (17329/17329), done.

real	2m13.389s
user	3m45.094s
sys	0m4.857s
```

I'm not entirely sure why the usual expected status output is missing, but I *think* sourceware only supports the "dumb http" protocol, not the "smart http" protocol, so you cannot get the special "remote: ...." status messages. Superficially, it seems to hang until all the way at the end when it completes.

I'm hesitant to switch from https:// to git://, because the former does TLS certificate validation. Are you sure it actually hangs for you? If you let it work for a few minutes, does it not complete?

**Comment by goddessfreya** [comment]
I just left it running for 1 hour, 50 minutes and 25 seconds. Ultimately, I had to do `git clone git://sourceware.org/git/glibc.git --bare /home/gentz/Documents/aur-buildscripts/ephemeral_dir/pkgbuilds.chroot/glibc-git-gentz.8b502a3391e92335fd882808c98b6e9c/glibc` to get it to work.

**Comment by goddessfreya** [comment]
Hmmm, alright, this is slightly odd: when I leave it up to `makepkg` to checkout the repos, no matter which link I use it will not complete. If I manually use `git clone --bare`, the git:// url will take ~2:50, while the http:// url will take ~4:00.

**Comment by eli-schwartz** [comment]
Well, I'm not sure how that happens. :/ That is truly bizarre.

Like I said -- it clones for me either way in about 2 minutes (for nearly 200MB data), and the only difference is that over https it doesn't show progress output until the very end.

**Comment by eli-schwartz** [comment]
> Hmmm, alright, this is slightly odd: when I leave it up to `makepkg` to checkout the repos, no matter which link I use it will not complete. If I manually use `git clone --bare`, the git:// url will take ~2:50, while the http:// url will take ~4:00.

Now that really confuses me, and I definitely cannot reproduce. I can successfully run makepkg --verifysource to get the glibc repository to clone.

**Comment by goddessfreya** [comment]
Huh, calling `makepkg --verifysource` worked for me, and so did my calls to `/home/gentz/Documents/aur-buildscripts/ephemeral_dir/custom.chroot/makechrootpkg <blah blah blah>`, but not when my script calls it....

**Comment by goddessfreya** [comment]
Alright, somehow this fixed it:
```diff
diff --git a/gabs-build-handler b/gabs-build-handler
index 65ed6eb..38a4d44 100755
--- a/gabs-build-handler
+++ b/gabs-build-handler
@@ -185,7 +189,7 @@ md5sum_files() {
 if [[ "${NO_BUILD}" != "true" ]]; then
     if ! "${MAKECHROOTPKG_BIN}" "${MAKECHROOTPKG_PARAMS[@]}" \
         -- CCACHE_DIR=/ccache "${MAKEPKG_PARAMS[@]}" \
-        2> >(tee data/makechrootpkgerrors 1>&2); then
+        2>(tee data/makechrootpkgerrors 1>&2); then
 
         local LINE_COUNT="$(( \
             $(md5sum_files \
```

The old code was swallowing stderr into the void, and somehow that made git hang for hours and not work. Or maybe it just conveniently timed out the two times (once to go watch a movie, and once last night) I left it running for longer than 2 minutes and would have worked all the other times?

**Comment by eli-schwartz** [comment]
Okay, I'm glad you figured it out, and even more glad I don't have to actually do anything. :D

(Actually, technically I do need to do something -- I need to rebase a patch file so it still applies. But that's a different story.)
