### ISSUE TITLE
Upgrade sigil-git to 1.4.2

### ISSUE THREAD

**Issue by RudiAusBuddeln** [eli-schwartz/pkgbuilds#19]
As clarified by a developer in https://github.com/Sigil-Ebook/Sigil/issues/574, Sigil 1.4.{0,1} should not be used.

Also, you might want to consider making `hunspell-en_US` a required dependency, since I did not check it because I am quite conservative about dependencies and the program became completely unusable. Or make it more obvious that the dictionary is not a simple spellchecker, which is what I supposed, but actually required for the interface.

**Comment by eli-schwartz** [comment]
The -git package always builds the latest git commit. It usually gets pkgver bumped whenever build changes are already occurring, but no guarantees other than that. The pkgver bump does nothing other than make AUR helpers think it is time to rebuild the package, you can still rebuild it all you want (e.g. by using the --devel flag most AUR helpers provide).

The official repo package is already updated.

**Comment by RudiAusBuddeln** [comment]
Then I'm just a victim of Manjaro rollout policy. Sorry for bothering you.
