### ISSUE TITLE
Post-commit hook fails after first commit

### ISSUE THREAD

**Issue by marcelkorpel** [eli-schwartz/pkgbuilds#2]
On line 4 of [post-commit.hook](https://github.com/eli-schwartz/pkgbuilds/blob/master/post-commit.hook#L4) there is a command

    git diff --name-only HEAD~1

However, this will fail with the following error message when I issue `git commit` in an empty repository:

>fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
>Use '--' to separate paths from revisions, like this:
>'git <command> [<revision>...] -- [<file>...]'

NOTE: I modified your hooks a bit to my liking (to support one-repo-per-package), but I'm rather sure this error will pop up on an otherwise empty repository with all packages in subdirectories. If not, I'm sorry for bothering you.

**Comment by eli-schwartz** [comment]
This hook assumes you are using my base branch with the one-repo-to-rule-them-all approach, it starts with a commit or two. :)
I do have a submodules branch which has hooks meant for one-repo-per-package. You might want to check that out.

I'm not too worried.
