### ISSUE TITLE
Probably false positive on 'nuke extraneous whitespace from orbit'

### ISSUE THREAD

**Issue by marcelkorpel** [eli-schwartz/pkgbuilds#3]
Is that step [`nuke extraneous whitespace from orbit`](https://github.com/eli-schwartz/pkgbuilds/blob/master/pre-commit.hook#L3) really necessary? You probably took it from the example hook, but now committing stops on a patch from [texlive-bin](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/fix-fontforge-encoding.patch?h=packages/texlive-bin):

```
fix-fontforge-encoding.patch:4: space before tab in indent.
+ 	{ "Big5HKSCS", e_big5hkscs },
fix-fontforge-encoding.patch:5: space before tab in indent.
+ 	{ "Big5-HKSCS", e_big5hkscs },
fix-fontforge-encoding.patch:6: space before tab in indent.
+ 	{ "UTF-8", e_utf8 },
fix-fontforge-encoding.patch:10: space before tab in indent.
+ 	{ "ISO-10646/UTF-8", e_utf8 },
fix-fontforge-encoding.patch:11: space before tab in indent.
+ 	{ "ISO_10646/UTF-8", e_utf8 },
fix-fontforge-encoding.patch:12: space before tab in indent.
+ 	{ "UCS2", e_unicode },
texlive.install:12: trailing whitespace.
+    echo      " done." 
texlive.install:34: trailing whitespace.
+        echo      " done." 
```

I think this is a false positive (the spaces should be really there). And I know the patch is commented out in PKGBUILD at the moment, but there may be other patches this hook doesn't accept.

For the record, this is about [texlive-bin-svn](https://aur.archlinux.org/packages/texlive-bin-svn/).

**Comment by eli-schwartz** [comment]
Ah, I had that in there because I myself have a vague horror of whitespace errors. I shouldn't be enforcing this on everyone else I suppose. Anyway, I didn't think about patches.

**Comment by eli-schwartz** [comment]
I changed my error to a red warning, and added that commit to the base branch too.
