### ISSUE TITLE
zfs-utils initcpio: Encryption support

### ISSUE THREAD

**Issue by stromnet** [eli-schwartz/pkgbuilds#30]
I've been trying to get native encryption working with root pool, something which https://wiki.archlinux.org/title/Install_Arch_Linux_on_ZFS#Configure_systemd_ZFS_mounts hints should be possible (at least it's talking about native encryption).

After many attempts I finally figured out that the zfs-utils package in AUR, which I opted for, is *not* the same as the zfs-utils package in the unoffical archzfs-linux ​repo. And the zfs-utils from that repo *does* have encryption support.

I noticed a few mentions relateing to this this on the zfs-utils discussion page https://aur.archlinux.org/packages/zfs-utils/?PP=250#comment-755817, but no issues or PRs in this repo.

Would it be acceptable to update the https://github.com/eli-schwartz/pkgbuilds/blob/master/zfs-utils/zfs.initcpio.hook with the encryption features (and possibly other changes, not sure what they do) from https://github.com/archzfs/archzfs/blob/master/src/zfs-utils/zfs-utils.initcpio.hook?

This would make it easier for me to manage my build of the zfs-utils pkg, and probably avoid lots of frustration for other users as well!

**Comment by BEvgeniyS** [comment]
Can we have this, please?

I have to replace `/usr/lib/initcpio/hooks/zfs` with the file from https://github.com/archzfs/archzfs/blob/5792ef65f5beea8d5fd1269fea12f08a85a5323b/src/zfs-utils/zfs-utils.initcpio.hook every update because the hook from the package lacks any decryption functions

**Comment by stromnet** [comment]
Closing, as new maintainer have added this :tada: 

https://aur.archlinux.org/packages/zfs-utils#comment-896628
