### ISSUE TITLE
Add updpkgsums to pre_commit_hook

### ISSUE THREAD

**Issue by rumpelsepp** [eli-schwartz/pkgbuilds#5]
What do you think about adding updpkgsums to the pre_commit_hook? I always forget this...

**Comment by eli-schwartz** [comment]
That makes me vaguely nervous, I prefer to test my packages first.
updpkgsums assumes you already know you have the right local files.

What about running `makepkg --verifysource -f` instead?
That way, it will check to make sure the checksums are correct, but if they aren't the commit fails and you are alerted to manually make sure of them.

**Comment by rumpelsepp** [comment]
On 25.01.2016 15:49, Eli Schwartz wrote:
> What about running |makepkg --verifysource -f| instead?
> That way, it will check to make sure the checksums are correct, but if
> they aren't the commit fails and you are alerted to manually make sure
> of them.

Sounds like a reasonable approach. :)
