### ISSUE TITLE
It is sometimes impossible to push to the AUR

### ISSUE THREAD

**Issue by zorun** [eli-schwartz/pkgbuilds#6]
From time to time, it is not possible to push a subtree to the AUR, even though the remote should be able to simply fast-forward:

```
$ ./aurpublish ring-gnome
git push using:  aur@aur.archlinux.org:ring-gnome.git master
To aur@aur.archlinux.org:ring-gnome.git
 ! [rejected]        28dffdb4433561c15fb6df5a4cb12cb1a15511f8 -> master (non-fast-forward)
error: failed to push some refs to 'aur@aur.archlinux.org:ring-gnome.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

When this happens, there is no apparent reason for the rejection: no commit has been pushed by another mean (no co-maintainer), and no rebase has been done locally.

This only happens infrequently, and I haven't found a reliable way to reproduce. My guess is that under some conditions, `git subtree` can generate different subtrees from the same git repository, and so the new subtree may have no common ancestor with the subtree in the AUR.  Maybe this can be caused by an upgrade of git?

I'm mostly opening this ticket for reference, I doubt this can be solved without finding a way to reproduce reliably (and maybe I _did_ do something locally that could explain the divergence).

**Comment by eli-schwartz** [comment]
I do know that git 2.5.1 fixed a bug with `git config log.date local` generating a localized history if you switch timezones: https://lists.archlinux.org/pipermail/aur-general/2015-August/031449.html

Maybe look at the git log for `28dffdb4433561c15fb6df5a4cb12cb1a15511f8` and see how it compares to the log for the AUR repo?
The subtree split should leave the ref available even though it hasn't been `--rejoin`ed to a branch.

**Comment by zorun** [comment]
Ok, thanks.  I will give it a try.
