### ISSUE TITLE
Support passing options to `aurpublish log`

### ISSUE THREAD

**Issue by ArchangeGabriel** [eli-schwartz/pkgbuilds#8]
For instance, I often use `-p` option to git’s `log`command, but here it results in:
`'-p' does not exist; use 'git subtree add'`

Not sure how hard that would be to implement in the script, I’m not a bash expert at all.

And thanks for this great work BTW! ;)

**Comment by eli-schwartz** [comment]
I hacked in support initially: `./aurpublish log $package "${logopts[@]"}`

Finding logopts **before** the pkgname (git itself supports either) would require more parsing than `package="${1%/}"; shift; do_stuff "$@"` but maybe I could do something...
Anyway, the usage could be clearer.

**Comment by ArchangeGabriel** [comment]
Oh, sure, didn’t try after the pkgname. I’m fine with this (even if it’s quite disturbing with regards to my habits), but this would indeed deserve a bit more documentation in the --help printing. ;)

**Comment by eli-schwartz** [comment]
Now it is less disturbing. :smile:

**Comment by ArchangeGabriel** [comment]
Thanks a lot! I’ve added a comment to your recent pushed changes related to the use of $pkgbase.
